spring:
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 6333e3a4e5d708
    password: fe8f96f51509f2
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true